app:
  name: hydrow-dashboard
  instances: 1
  group: hydrow-dashboard
  fqdn: hydrow.nickknows.net
  image: docker.io/ncging/hydrow-dashboard:sha-f01e0c6
  port: 8000
redis:
  name: hydrow-web-redis
  image: redis:8.6.2
  port: 6379
